sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: zhs20021018
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5t6SUdPkfJJDVoTWQDdw
    access-key-secret: woqWp94lzIJ6nXjRZZbkOLJHAenNtj
    bucket-name: it-picture
  redis:
    host: localhost
    port: 6379
    password: zhs20021018
    database: 1
  wechat:
    appid: wxf40f26365f110fa4
    secret: 3eeb58bfcb604cbec955248ad31a89fc